const { Tellraw, Text } = require('./../utils/tellraw.js');
const config = require('./../config.json');
const { setTimeout: sleep } = require('timers/promises');
const casual = require('casual');

const modernBackgrounds = [
    "Software Engineer",
    "Graphic Designer",
    "Chef",
    "Journalist",
    "Barista",
    "Police Officer",
    "Doctor",
    "Entrepreneur",
    "Musician",
    "Freelancer",
    "Teacher",
    "Fitness Trainer",
    "Social Media Influencer",
    "Actor/Actress",
    "Fashion Designer",
    "Travel Blogger",
    "Marketing Executive",
    "Banker",
    "Stay-at-home Parent",
    "Retail Worker"
    // Add more modern backgrounds as needed
  ];

const hobbies = [
    "Reading",
    "Writing",
    "Painting",
    "Hiking",
    "Cooking",
    "Photography",
    "Playing musical instruments",
    "Gardening",
    "Coding",
    "Dancing",
    "Traveling",
    "Knitting/Crocheting",
    "Yoga",
    "Fishing",
    "Birdwatching",
    "Woodworking",
    "Meditation",
    "Sculpting",
    "Gaming",
    "Collecting stamps/coins",
    "Baking",
    "Calligraphy",
    "Rock climbing",
    "Singing",
    "Skydiving",
    "Cycling",
    "Swimming",
    "Running",
    "Pottery",
    "Film-making",
    "Origami",
    "Chess",
    "Scuba diving",
    "Astrophotography",
    "Archery",
    "DIY projects",
    "Volunteering",
    "Stargazing",
    "Fashion designing",
    "Board games",
    "Camping",
    "Model building",
    "Playing sports (e.g., soccer, basketball, tennis)",
    "Learning new languages",
    "Beekeeping",
    "Metal detecting",
    "Fossil hunting",
    "Geocaching",
    "Ghost hunting",
    "Whittling",
    "Surfing",
    "Kite flying",
    "Paragliding",
    "Beer brewing",
    "Skiing/Snowboarding",
    "Whale watching",
    "Sudoku",
    "Crossword puzzles",
    "Jigsaw puzzles",
    "Candle making",
    "Tea blending",
    "Foraging",
    "Caving",
    "Karaoke",
    "Writing poetry",
    "Playing board games",
    "Reading tarot cards",
    "Studying history",
    "Building models",
    "Graffiti art",
    "Bungee jumping",
    "Mountaineering",
    "Amateur radio",
    "Genealogy",
    "Soap making",
    "Magic tricks",
    "Metalworking",
    "Trampolining",
    "Aquarium keeping",
    "Horseback riding",
    "Calligraphy",
    "Belly dancing",
    "Sewing",
    "Antiquing",
    "Photography",
    "Stained glass making",
    "Beekeeping",
    "Archery",
    "DJing",
    "Martial arts",
    "Glassblowing",
    "Canoeing/Kayaking",
    "Jewelry making",
    "Paddleboarding",
    "Snorkeling",
    "Trekking",
    "Astrology",
    "Board games",
    "Model rocketry",
    "Table tennis",
    "Quilting",
    "Ghost hunting",
    "Wine tasting",
    "Astronomy",
    "Metal detecting",
    "Beekeeping",
    "Bodybuilding",
    "Ghost hunting",
    "Archery",
    "Geocaching",
    "Paintball",
    "Calligraphy",
    "Whale watching",
    "Whittling",
    "Graffiti art",
    "Karaoke",
    "Metalworking",
    "Photography",
    "Board games",
    "Candle making",
    "Foraging",
    "Reading tarot cards",
    "Surfing",
    "Studying history",
    "Genealogy",
    "Mountaineering",
    "Soap making",
    "Aquarium keeping",
    "Amateur radio",
    "Antiquing",
    "Astrology",
    "Beekeeping",
    "Belly dancing",
    "DJing",
    "Glassblowing",
    "Horseback riding",
    "Martial arts",
    "Soap making",
    "Archery",
    "Whale watching",
    "Photography",
    "Foraging",
    "Model rocketry",
    "Astrology",
    "Metal detecting",
    "Astronomy",
    "Beekeeping",
    "Ghost hunting",
    "Calligraphy",
    "Geocaching",
    "Whale watching",
    "Graffiti art",
    "Karaoke",
    "Whittling",
    "Reading tarot cards",
    "Bodybuilding",
    "Surfing",
    "Metalworking",
    "Studying history",
    "Antiquing",
    "Aquarium keeping",
    "Soap making",
    "Mountaineering",
    "Genealogy",
    "Martial arts",
    "DJing",
    "Horseback riding",
    "Belly dancing",
    "Glassblowing",
    "Amateur radio",
    "Astrology",
    "Beekeeping",
    "Antiquing",
    "Archery",
    "Photography",
    "Foraging",
    "Ghost hunting",
    "Calligraphy",
    "Whale watching",
    "Geocaching",
    "Metal detecting",
    "Graffiti art",
    "Whittling",
    "Karaoke",
    "Reading tarot cards",
    "Bodybuilding",
    "Mountaineering",
    "Surfing",
    "Studying history",
    "Aquarium keeping",
    "Soap making",
    "Antiquing",
    "Martial arts",
    "Astrology",
    "DJing",
    "Glassblowing",
    "Genealogy",
    "Horseback riding",
    "Belly dancing",
    "Amateur radio",
    "Beekeeping",
    "Astrology",
    "Antiquing",
    "Archery",
    "Photography",
    "Foraging",
    "Ghost hunting",
    "Calligraphy",
    "Whale watching",
    "Geocaching",
    "Metal detecting",
    "Graffiti art",
    "Whittling",
    "Karaoke",
    "Reading tarot cards",
    "Bodybuilding",
    "Mountaineering",
    "Surfing",
    "Studying history",
    "Aquarium keeping",
    "Soap making",
    "Antiquing",
    "Martial arts",
    "Astrology",
    "DJing",
    "Glassblowing",
    "Genealogy",
    "Horseback riding",
    "Belly dancing",
    "Amateur radio",
    "Beekeeping",
    "Astrology",
    "Antiquing",
    "Archery",
    "Photography",
    "Foraging",
    "Ghost hunting",
    "Calligraphy",
    "Whale watching",
    "Geocaching",
    "Metal detecting",
    "Graffiti art",
    "Whittling",
    "Karaoke",
    "Reading tarot cards",
    "Bodybuilding",
    "Mountaineering",
    "Surfing",
    "Studying history",
    "Aquarium keeping",
    "Soap making",
    "Antiquing",
    "Martial arts",
    "Astrology",
    "DJing",
    "Glassblowing",
    "Genealogy",
    "Horseback riding",
    "Belly dancing",
    "Amateur radio",
    "Beekeeping",
    "Astrology",
    "Antiquing",
    "Archery"
] 

module.exports = {
    name: "fakeid",
    aliases: ['fid', 'faker'],
    description: "Generates a fake id",
    usages: [`fakeid`],    
    permissionLevel: "0",
    working: true,
    async execute(context) {
        const colors = context.config.colors;
        try {
            const core = context.core;

            const age = casual.integer(from = 18, to = 90);
            const gender = casual.random_element(['Male', 'Female']);
            const firstName = casual.first_name;
            const middleName = casual.first_name;
            const lastName = casual.last_name;
            const race = casual.random_element(['Caucasian', 'African American', 'Asian', 'Hispanic', 'Other']);
            const religion = casual.random_element(['Christianity', 'Islam', 'Hinduism', 'Buddhism', 'Judaism', 'Other']);
            const randomIndex = Math.floor(Math.random() * modernBackgrounds.length);
            const job = modernBackgrounds[randomIndex];
            const randomIndexHobbies = Math.floor(Math.random() * hobbies.length);
            const hobbiesFinal = hobbies[randomIndexHobbies];
            const location = casual.city;
            
            core.run((new Tellraw("@a", [
                new Text(`\n`).setColor(colors.primary),
                new Text(`Age: ${age}\n`).setColor(colors.primary),
                new Text(`Gender: ${gender}\n`).setColor(colors.primary),
                new Text(`First Name: ${firstName}\n`).setColor(colors.primary),
                new Text(`Middle Name: ${middleName}\n`).setColor(colors.primary),
                new Text(`Last Name: ${lastName}\n`).setColor(colors.primary),
                new Text(`Race: ${race}\n`).setColor(colors.primary),
                new Text(`Religion: ${religion}\n`).setColor(colors.primary),
                new Text(`Hobbie: ${hobbiesFinal}\n`).setColor(colors.primary),
                new Text(`Lives in: ${location}\n`).setColor(colors.primary),
                new Text(`Job: ${job}`).setColor(colors.primary),
            ])).get());            

        } catch (error) {
            const core = context.core
            core.run((new Tellraw("@a", [new Text(`ERROR - ` + error).setColor(colors.errorColor).setHover(error.stack).setCopy(error.stack)])).get());
        }
        return context;
    }
};