const { Tellraw, Text } = require('./../utils/tellraw.js');
const config = require('./../config.json');
const { setTimeout: sleep } = require('timers/promises');

module.exports = {
    name: "randomloot",
    aliases: ['rl'],
    description: "Generates a chest of random loot",
    usages: [
        'randomLoot'
    ],
    permissionLevel: "0",
    working: true,
    async execute(context) {
        const colors = context.config.colors;
        try {
            const core = context.core;
            const senderUUID = context.senderUUID

            function getRandomInt(min, max) {
                return Math.floor(Math.random() * (max - min)) + min;
            }

            function generateRandomChest() {
                const items = [
                    { id: "stone", count: [1, 64] },
                    { id: "granite", count: [1, 64] },
                    { id: "polished_granite", count: [1, 64] },
                    { id: "diorite", count: [1, 64] },
                    { id: "polished_diorite", count: [1, 64] },
                    { id: "andesite", count: [1, 64] },
                    { id: "polished_andesite", count: [1, 64] },
                    { id: "grass_block", count: [1, 64] },
                    { id: "dirt", count: [1, 64] },
                    { id: "coarse_dirt", count: [1, 64] },
                    { id: "podzol", count: [1, 64] },
                    { id: "cobblestone", count: [1, 64] },
                    { id: "oak_planks", count: [1, 64] },
                    { id: "spruce_planks", count: [1, 64] },
                    { id: "birch_planks", count: [1, 64] },
                    { id: "jungle_planks", count: [1, 64] },
                    { id: "acacia_planks", count: [1, 64] },
                    { id: "dark_oak_planks", count: [1, 64] },
                    { id: "oak_sapling", count: [1, 64] },
                    { id: "spruce_sapling", count: [1, 64] },
                    { id: "birch_sapling", count: [1, 64] },
                    { id: "jungle_sapling", count: [1, 64] },
                    { id: "acacia_sapling", count: [1, 64] },
                    { id: "dark_oak_sapling", count: [1, 64] },
                    { id: "bedrock", count: [1, 64] },
                    { id: "sand", count: [1, 64] },
                    { id: "red_sand", count: [1, 64] },
                    { id: "gravel", count: [1, 64] },
                    { id: "gold_ore", count: [1, 64] },
                    { id: "iron_ore", count: [1, 64] },
                    { id: "coal_ore", count: [1, 64] },
                    { id: "oak_log", count: [1, 64] },
                    { id: "spruce_log", count: [1, 64] },
                    { id: "birch_log", count: [1, 64] },
                    { id: "jungle_log", count: [1, 64] },
                    { id: "acacia_log", count: [1, 64] },
                    { id: "dark_oak_log", count: [1, 64] },
                    { id: "stripped_oak_log", count: [1, 64] },
                    { id: "stripped_spruce_log", count: [1, 64] },
                    { id: "stripped_birch_log", count: [1, 64] },
                    { id: "stripped_jungle_log", count: [1, 64] },
                    { id: "stripped_acacia_log", count: [1, 64] },
                    { id: "stripped_dark_oak_log", count: [1, 64] },
                    { id: "stripped_oak_wood", count: [1, 64] },
                    { id: "stripped_spruce_wood", count: [1, 64] },
                    { id: "stripped_birch_wood", count: [1, 64] },
                    { id: "stripped_jungle_wood", count: [1, 64] },
                    { id: "stripped_acacia_wood", count: [1, 64] },
                    { id: "stripped_dark_oak_wood", count: [1, 64] },
                    { id: "oak_wood", count: [1, 64] },
                    { id: "spruce_wood", count: [1, 64] },
                    { id: "birch_wood", count: [1, 64] },
                    { id: "jungle_wood", count: [1, 64] },
                    { id: "acacia_wood", count: [1, 64] },
                    { id: "dark_oak_wood", count: [1, 64] },
                    { id: "oak_leaves", count: [1, 64] },
                    { id: "spruce_leaves", count: [1, 64] },
                    { id: "birch_leaves", count: [1, 64] },
                    { id: "jungle_leaves", count: [1, 64] },
                    { id: "acacia_leaves", count: [1, 64] },
                    { id: "dark_oak_leaves", count: [1, 64] },
                    { id: "sponge", count: [1, 64] },
                    { id: "wet_sponge", count: [1, 64] },
                    { id: "glass", count: [1, 64] },
                    { id: "lapis_ore", count: [1, 64] },
                    { id: "lapis_block", count: [1, 64] },
                    { id: "dispenser", count: [1, 64] },
                    { id: "sandstone", count: [1, 64] },
                    { id: "chiseled_sandstone", count: [1, 64] },
                    { id: "cut_sandstone", count: [1, 64] },
                    { id: "note_block", count: [1, 64] },
                    { id: "powered_rail", count: [1, 64] },
                    { id: "detector_rail", count: [1, 64] },
                    { id: "sticky_piston", count: [1, 64] },
                    { id: "cobweb", count: [1, 64] },
                    { id: "grass", count: [1, 64] },
                    { id: "fern", count: [1, 64] },
                    { id: "dead_bush", count: [1, 64] },
                    { id: "seagrass", count: [1, 64] },
                    { id: "sea_pickle", count: [1, 64] },
                    { id: "piston", count: [1, 64] },
                    { id: "white_wool", count: [1, 64] },
                    { id: "orange_wool", count: [1, 64] },
                    { id: "magenta_wool", count: [1, 64] },
                    { id: "light_blue_wool", count: [1, 64] },
                    { id: "yellow_wool", count: [1, 64] },
                    { id: "lime_wool", count: [1, 64] },
                    { id: "pink_wool", count: [1, 64] },
                    { id: "gray_wool", count: [1, 64] },
                    { id: "light_gray_wool", count: [1, 64] },
                    { id: "cyan_wool", count: [1, 64] },
                    { id: "purple_wool", count: [1, 64] },
                    { id: "blue_wool", count: [1, 64] },
                    { id: "brown_wool", count: [1, 64] },
                    { id: "green_wool", count: [1, 64] },
                    { id: "red_wool", count: [1, 64] },
                    { id: "black_wool", count: [1, 64] },
                    { id: "dandelion", count: [1, 64] },
                    { id: "poppy", count: [1, 64] },
                    { id: "blue_orchid", count: [1, 64] },
                    { id: "allium", count: [1, 64] },
                    { id: "azure_bluet", count: [1, 64] },
                    { id: "red_tulip", count: [1, 64] },
                    { id: "orange_tulip", count: [1, 64] },
                    { id: "white_tulip", count: [1, 64] },
                    { id: "pink_tulip", count: [1, 64] },
                    { id: "oxeye_daisy", count: [1, 64] },
                    { id: "cornflower", count: [1, 64] },
                    { id: "lily_of_the_valley", count: [1, 64] },
                    { id: "wither_rose", count: [1, 64] },
                    { id: "brown_mushroom", count: [1, 64] },
                    { id: "red_mushroom", count: [1, 64] },
                    { id: "gold_block", count: [1, 64] },
                    { id: "iron_block", count: [1, 64] },
                    { id: "oak_slab", count: [1, 64] },
                    { id: "spruce_slab", count: [1, 64] },
                    { id: "birch_slab", count: [1, 64] },
                    { id: "jungle_slab", count: [1, 64] },
                    { id: "acacia_slab", count: [1, 64] },
                    { id: "dark_oak_slab", count: [1, 64] },
                    { id: "stone_slab", count: [1, 64] },
                    { id: "smooth_stone_slab", count: [1, 64] },
                    { id: "sandstone_slab", count: [1, 64] },
                    { id: "cut_sandstone_slab", count: [1, 64] },
                    { id: "petrified_oak_slab", count: [1, 64] },
                    { id: "cobblestone_slab", count: [1, 64] },
                    { id: "brick_slab", count: [1, 64] },
                    { id: "stone_brick_slab", count: [1, 64] },
                    { id: "nether_brick_slab", count: [1, 64] },
                    { id: "quartz_slab", count: [1, 64] },
                    { id: "red_sandstone_slab", count: [1, 64] },
                    { id: "cut_red_sandstone_slab", count: [1, 64] },
                    { id: "purpur_slab", count: [1, 64] },
                    { id: "prismarine_slab", count: [1, 64] },
                    { id: "prismarine_brick_slab", count: [1, 64] },
                    { id: "dark_prismarine_slab", count: [1, 64] },
                    { id: "smooth_quartz", count: [1, 64] },
                    { id: "smooth_red_sandstone", count: [1, 64] },
                    { id: "smooth_sandstone", count: [1, 64] },
                    { id: "smooth_stone", count: [1, 64] },
                    { id: "bricks", count: [1, 64] },
                    { id: "tnt", count: [1, 64] },
                    { id: "bookshelf", count: [1, 64] },
                    { id: "mossy_cobblestone", count: [1, 64] },
                    { id: "obsidian", count: [1, 64] },
                    { id: "torch", count: [1, 64] },
                    { id: "end_rod", count: [1, 64] },
                    { id: "chorus_plant", count: [1, 64] },
                    { id: "chorus_flower", count: [1, 64] },
                    { id: "purpur_block", count: [1, 64] },
                    { id: "purpur_pillar", count: [1, 64] },
                    { id: "purpur_stairs", count: [1, 64] },
                    { id: "spawner", count: [1, 64] },
                    { id: "oak_stairs", count: [1, 64] },
                    { id: "chest", count: [1, 64] },
                    { id: "diamond_ore", count: [1, 64] },
                    { id: "diamond_block", count: [1, 64] },
                    { id: "crafting_table", count: [1, 64] },
                    { id: "farmland", count: [1, 64] },
                    { id: "furnace", count: [1, 64] },
                    { id: "ladder", count: [1, 64] },
                    { id: "rail", count: [1, 64] },
                    { id: "cobblestone_stairs", count: [1, 64] },
                    { id: "lever", count: [1, 64] },
                    { id: "stone_pressure_plate", count: [1, 64] },
                    { id: "oak_pressure_plate", count: [1, 64] },
                    { id: "spruce_pressure_plate", count: [1, 64] },
                    { id: "birch_pressure_plate", count: [1, 64] },
                    { id: "jungle_pressure_plate", count: [1, 64] },
                    { id: "acacia_pressure_plate", count: [1, 64] },
                    { id: "dark_oak_pressure_plate", count: [1, 64] },
                    { id: "redstone_ore", count: [1, 64] },
                    { id: "redstone_torch", count: [1, 64] },
                    { id: "stone_button", count: [1, 64] },
                    { id: "snow", count: [1, 64] },
                    { id: "ice", count: [1, 64] },
                    { id: "snow_block", count: [1, 64] },
                    { id: "cactus", count: [1, 64] },
                    { id: "clay", count: [1, 64] },
                    { id: "jukebox", count: [1, 64] },
                    { id: "oak_fence", count: [1, 64] },
                    { id: "spruce_fence", count: [1, 64] },
                    { id: "birch_fence", count: [1, 64] },
                    { id: "jungle_fence", count: [1, 64] },
                    { id: "acacia_fence", count: [1, 64] },
                    { id: "dark_oak_fence", count: [1, 64] },
                    { id: "pumpkin", count: [1, 64] },
                    { id: "carved_pumpkin", count: [1, 64] },
                    { id: "netherrack", count: [1, 64] },
                    { id: "soul_sand", count: [1, 64] },
                    { id: "glowstone", count: [1, 64] },
                    { id: "jack_o_lantern", count: [1, 64] },
                    { id: "oak_trapdoor", count: [1, 64] },
                    { id: "spruce_trapdoor", count: [1, 64] },
                    { id: "birch_trapdoor", count: [1, 64] },
                    { id: "jungle_trapdoor", count: [1, 64] },
                    { id: "acacia_trapdoor", count: [1, 64] },
                    { id: "dark_oak_trapdoor", count: [1, 64] },
                    { id: "infested_stone", count: [1, 64] },
                    { id: "infested_cobblestone", count: [1, 64] },
                    { id: "infested_stone_bricks", count: [1, 64] },
                    { id: "infested_mossy_stone_bricks", count: [1, 64] },
                    { id: "infested_cracked_stone_bricks", count: [1, 64] },
                    { id: "infested_chiseled_stone_bricks", count: [1, 64] },
                    { id: "stone_bricks", count: [1, 64] },
                    { id: "mossy_stone_bricks", count: [1, 64] },
                    { id: "cracked_stone_bricks", count: [1, 64] },
                    { id: "chiseled_stone_bricks", count: [1, 64] },
                    { id: "brown_mushroom_block", count: [1, 64] },
                    { id: "red_mushroom_block", count: [1, 64] },
                    { id: "mushroom_stem", count: [1, 64] },
                    { id: "iron_bars", count: [1, 64] },
                    { id: "glass_pane", count: [1, 64] },
                    { id: "melon", count: [1, 64] },
                    { id: "vine", count: [1, 64] },
                    { id: "oak_fence_gate", count: [1, 64] },
                    { id: "spruce_fence_gate", count: [1, 64] },
                    { id: "birch_fence_gate", count: [1, 64] },
                    { id: "jungle_fence_gate", count: [1, 64] },
                    { id: "acacia_fence_gate", count: [1, 64] },
                    { id: "dark_oak_fence_gate", count: [1, 64] },
                    { id: "brick_stairs", count: [1, 64] },
                    { id: "stone_brick_stairs", count: [1, 64] },
                    { id: "mycelium", count: [1, 64] },
                    { id: "lily_pad", count: [1, 64] },
                    { id: "nether_bricks", count: [1, 64] },
                    { id: "nether_brick_fence", count: [1, 64] },
                    { id: "nether_brick_stairs", count: [1, 64] },
                    { id: "enchanting_table", count: [1, 64] },
                    { id: "end_portal_frame", count: [1, 64] },
                    { id: "end_stone", count: [1, 64] },
                    { id: "end_stone_bricks", count: [1, 64] },
                    { id: "dragon_egg", count: [1, 64] },
                    { id: "redstone_lamp", count: [1, 64] },
                    { id: "sandstone_stairs", count: [1, 64] },
                    { id: "emerald_ore", count: [1, 64] },
                    { id: "ender_chest", count: [1, 64] },
                    { id: "tripwire_hook", count: [1, 64] },
                    { id: "emerald_block", count: [1, 64] },
                    { id: "spruce_stairs", count: [1, 64] },
                    { id: "birch_stairs", count: [1, 64] },
                    { id: "jungle_stairs", count: [1, 64] },
                    { id: "command_block", count: [1, 64] },
                    { id: "beacon", count: [1, 64] },
                    { id: "cobblestone_wall", count: [1, 64] },
                    { id: "mossy_cobblestone_wall", count: [1, 64] },
                    { id: "brick_wall", count: [1, 64] },
                    { id: "prismarine_wall", count: [1, 64] },
                    { id: "red_sandstone_wall", count: [1, 64] },
                    { id: "mossy_stone_brick_wall", count: [1, 64] },
                    { id: "granite_wall", count: [1, 64] },
                    { id: "stone_brick_wall", count: [1, 64] },
                    { id: "nether_brick_wall", count: [1, 64] },
                    { id: "andesite_wall", count: [1, 64] },
                    { id: "red_nether_brick_wall", count: [1, 64] },
                    { id: "sandstone_wall", count: [1, 64] },
                    { id: "end_stone_brick_wall", count: [1, 64] },
                    { id: "diorite_wall", count: [1, 64] },
                    { id: "oak_button", count: [1, 64] },
                    { id: "spruce_button", count: [1, 64] },
                    { id: "birch_button", count: [1, 64] },
                    { id: "jungle_button", count: [1, 64] },
                    { id: "acacia_button", count: [1, 64] },
                    { id: "dark_oak_button", count: [1, 64] },
                    { id: "anvil", count: [1, 64] },
                    { id: "chipped_anvil", count: [1, 64] },
                    { id: "damaged_anvil", count: [1, 64] },
                    { id: "trapped_chest", count: [1, 64] },
                    { id: "light_weighted_pressure_plate", count: [1, 64] },
                    { id: "heavy_weighted_pressure_plate", count: [1, 64] },
                    { id: "daylight_detector", count: [1, 64] },
                    { id: "redstone_block", count: [1, 64] },
                    { id: "nether_quartz_ore", count: [1, 64] },
                    { id: "hopper", count: [1, 64] },
                    { id: "chiseled_quartz_block", count: [1, 64] },
                    { id: "quartz_block", count: [1, 64] },
                    { id: "quartz_pillar", count: [1, 64] },
                    { id: "quartz_stairs", count: [1, 64] },
                    { id: "activator_rail", count: [1, 64] },
                    { id: "dropper", count: [1, 64] },
                    { id: "white_terracotta", count: [1, 64] },
                    { id: "orange_terracotta", count: [1, 64] },
                    { id: "magenta_terracotta", count: [1, 64] },
                    { id: "light_blue_terracotta", count: [1, 64] },
                    { id: "yellow_terracotta", count: [1, 64] },
                    { id: "lime_terracotta", count: [1, 64] },
                    { id: "pink_terracotta", count: [1, 64] },
                    { id: "gray_terracotta", count: [1, 64] },
                    { id: "light_gray_terracotta", count: [1, 64] },
                    { id: "cyan_terracotta", count: [1, 64] },
                    { id: "purple_terracotta", count: [1, 64] },
                    { id: "blue_terracotta", count: [1, 64] },
                    { id: "brown_terracotta", count: [1, 64] },
                    { id: "green_terracotta", count: [1, 64] },
                    { id: "red_terracotta", count: [1, 64] },
                    { id: "black_terracotta", count: [1, 64] },
                    { id: "barrier", count: [1, 64] },
                    { id: "iron_trapdoor", count: [1, 64] },
                    { id: "hay_block", count: [1, 64] },
                    { id: "white_carpet", count: [1, 64] },
                    { id: "orange_carpet", count: [1, 64] },
                    { id: "magenta_carpet", count: [1, 64] },
                    { id: "light_blue_carpet", count: [1, 64] },
                    { id: "yellow_carpet", count: [1, 64] },
                    { id: "lime_carpet", count: [1, 64] },
                    { id: "pink_carpet", count: [1, 64] },
                    { id: "gray_carpet", count: [1, 64] },
                    { id: "light_gray_carpet", count: [1, 64] },
                    { id: "cyan_carpet", count: [1, 64] },
                    { id: "purple_carpet", count: [1, 64] },
                    { id: "blue_carpet", count: [1, 64] },
                    { id: "brown_carpet", count: [1, 64] },
                    { id: "green_carpet", count: [1, 64] },
                    { id: "red_carpet", count: [1, 64] },
                    { id: "black_carpet", count: [1, 64] },
                    { id: "terracotta", count: [1, 64] },
                    { id: "coal_block", count: [1, 64] },
                    { id: "packed_ice", count: [1, 64] },
                    { id: "acacia_stairs", count: [1, 64] },
                    { id: "dark_oak_stairs", count: [1, 64] },
                    { id: "slime_block", count: [1, 64] },
                    { id: "grass_path", count: [1, 64] },
                    { id: "sunflower", count: [1, 64] },
                    { id: "lilac", count: [1, 64] },
                    { id: "rose_bush", count: [1, 64] },
                    { id: "peony", count: [1, 64] },
                    { id: "tall_grass", count: [1, 64] },
                    { id: "large_fern", count: [1, 64] },
                    { id: "white_stained_glass", count: [1, 64] },
                    { id: "orange_stained_glass", count: [1, 64] },
                    { id: "magenta_stained_glass", count: [1, 64] },
                    { id: "light_blue_stained_glass", count: [1, 64] },
                    { id: "yellow_stained_glass", count: [1, 64] },
                    { id: "lime_stained_glass", count: [1, 64] },
                    { id: "pink_stained_glass", count: [1, 64] },
                    { id: "gray_stained_glass", count: [1, 64] },
                    { id: "light_gray_stained_glass", count: [1, 64] },
                    { id: "cyan_stained_glass", count: [1, 64] },
                    { id: "purple_stained_glass", count: [1, 64] },
                    { id: "blue_stained_glass", count: [1, 64] },
                    { id: "brown_stained_glass", count: [1, 64] },
                    { id: "green_stained_glass", count: [1, 64] },
                    { id: "red_stained_glass", count: [1, 64] },
                    { id: "black_stained_glass", count: [1, 64] },
                    { id: "white_stained_glass_pane", count: [1, 64] },
                    { id: "orange_stained_glass_pane", count: [1, 64] },
                    { id: "magenta_stained_glass_pane", count: [1, 64] },
                    { id: "light_blue_stained_glass_pane", count: [1, 64] },
                    { id: "yellow_stained_glass_pane", count: [1, 64] },
                    { id: "lime_stained_glass_pane", count: [1, 64] },
                    { id: "pink_stained_glass_pane", count: [1, 64] },
                    { id: "gray_stained_glass_pane", count: [1, 64] },
                    { id: "light_gray_stained_glass_pane", count: [1, 64] },
                    { id: "cyan_stained_glass_pane", count: [1, 64] },
                    { id: "purple_stained_glass_pane", count: [1, 64] },
                    { id: "blue_stained_glass_pane", count: [1, 64] },
                    { id: "brown_stained_glass_pane", count: [1, 64] },
                    { id: "green_stained_glass_pane", count: [1, 64] },
                    { id: "red_stained_glass_pane", count: [1, 64] },
                    { id: "black_stained_glass_pane", count: [1, 64] },
                    { id: "prismarine", count: [1, 64] },
                    { id: "prismarine_bricks", count: [1, 64] },
                    { id: "dark_prismarine", count: [1, 64] },
                    { id: "prismarine_stairs", count: [1, 64] },
                    { id: "prismarine_brick_stairs", count: [1, 64] },
                    { id: "dark_prismarine_stairs", count: [1, 64] },
                    { id: "sea_lantern", count: [1, 64] },
                    { id: "red_sandstone", count: [1, 64] },
                    { id: "chiseled_red_sandstone", count: [1, 64] },
                    { id: "cut_red_sandstone", count: [1, 64] },
                    { id: "red_sandstone_stairs", count: [1, 64] },
                    { id: "repeating_command_block", count: [1, 64] },
                    { id: "chain_command_block", count: [1, 64] },
                    { id: "magma_block", count: [1, 64] },
                    { id: "nether_wart_block", count: [1, 64] },
                    { id: "red_nether_bricks", count: [1, 64] },
                    { id: "bone_block", count: [1, 64] },
                    { id: "structure_void", count: [1, 64] },
                    { id: "observer", count: [1, 64] },
                    { id: "shulker_box", count: [1, 64] },
                    { id: "white_shulker_box", count: [1, 64] },
                    { id: "orange_shulker_box", count: [1, 64] },
                    { id: "magenta_shulker_box", count: [1, 64] },
                    { id: "light_blue_shulker_box", count: [1, 64] },
                    { id: "yellow_shulker_box", count: [1, 64] },
                    { id: "lime_shulker_box", count: [1, 64] },
                    { id: "pink_shulker_box", count: [1, 64] },
                    { id: "gray_shulker_box", count: [1, 64] },
                    { id: "light_gray_shulker_box", count: [1, 64] },
                    { id: "cyan_shulker_box", count: [1, 64] },
                    { id: "purple_shulker_box", count: [1, 64] },
                    { id: "blue_shulker_box", count: [1, 64] },
                    { id: "brown_shulker_box", count: [1, 64] },
                    { id: "green_shulker_box", count: [1, 64] },
                    { id: "red_shulker_box", count: [1, 64] },
                    { id: "black_shulker_box", count: [1, 64] },
                    { id: "white_glazed_terracotta", count: [1, 64] },
                    { id: "orange_glazed_terracotta", count: [1, 64] },
                    { id: "magenta_glazed_terracotta", count: [1, 64] },
                    { id: "light_blue_glazed_terracotta", count: [1, 64] },
                    { id: "yellow_glazed_terracotta", count: [1, 64] },
                    { id: "lime_glazed_terracotta", count: [1, 64] },
                    { id: "pink_glazed_terracotta", count: [1, 64] },
                    { id: "gray_glazed_terracotta", count: [1, 64] },
                    { id: "light_gray_glazed_terracotta", count: [1, 64] },
                    { id: "cyan_glazed_terracotta", count: [1, 64] },
                    { id: "purple_glazed_terracotta", count: [1, 64] },
                    { id: "blue_glazed_terracotta", count: [1, 64] },
                    { id: "brown_glazed_terracotta", count: [1, 64] },
                    { id: "green_glazed_terracotta", count: [1, 64] },
                    { id: "red_glazed_terracotta", count: [1, 64] },
                    { id: "black_glazed_terracotta", count: [1, 64] },
                    { id: "white_concrete", count: [1, 64] },
                    { id: "orange_concrete", count: [1, 64] },
                    { id: "magenta_concrete", count: [1, 64] },
                    { id: "light_blue_concrete", count: [1, 64] },
                    { id: "yellow_concrete", count: [1, 64] },
                    { id: "lime_concrete", count: [1, 64] },
                    { id: "pink_concrete", count: [1, 64] },
                    { id: "gray_concrete", count: [1, 64] },
                    { id: "light_gray_concrete", count: [1, 64] },
                    { id: "cyan_concrete", count: [1, 64] },
                    { id: "purple_concrete", count: [1, 64] },
                    { id: "blue_concrete", count: [1, 64] },
                    { id: "brown_concrete", count: [1, 64] },
                    { id: "green_concrete", count: [1, 64] },
                    { id: "red_concrete", count: [1, 64] },
                    { id: "black_concrete", count: [1, 64] },
                    { id: "white_concrete_powder", count: [1, 64] },
                    { id: "orange_concrete_powder", count: [1, 64] },
                    { id: "magenta_concrete_powder", count: [1, 64] },
                    { id: "light_blue_concrete_powder", count: [1, 64] },
                    { id: "yellow_concrete_powder", count: [1, 64] },
                    { id: "lime_concrete_powder", count: [1, 64] },
                    { id: "pink_concrete_powder", count: [1, 64] },
                    { id: "gray_concrete_powder", count: [1, 64] },
                    { id: "light_gray_concrete_powder", count: [1, 64] },
                    { id: "cyan_concrete_powder", count: [1, 64] },
                    { id: "purple_concrete_powder", count: [1, 64] },
                    { id: "blue_concrete_powder", count: [1, 64] },
                    { id: "brown_concrete_powder", count: [1, 64] },
                    { id: "green_concrete_powder", count: [1, 64] },
                    { id: "red_concrete_powder", count: [1, 64] },
                    { id: "black_concrete_powder", count: [1, 64] },
                    { id: "turtle_egg", count: [1, 64] },
                    { id: "dead_tube_coral_block", count: [1, 64] },
                    { id: "dead_brain_coral_block", count: [1, 64] },
                    { id: "dead_bubble_coral_block", count: [1, 64] },
                    { id: "dead_fire_coral_block", count: [1, 64] },
                    { id: "dead_horn_coral_block", count: [1, 64] },
                    { id: "tube_coral_block", count: [1, 64] },
                    { id: "brain_coral_block", count: [1, 64] },
                    { id: "bubble_coral_block", count: [1, 64] },
                    { id: "fire_coral_block", count: [1, 64] },
                    { id: "horn_coral_block", count: [1, 64] },
                    { id: "tube_coral", count: [1, 64] },
                    { id: "brain_coral", count: [1, 64] },
                    { id: "bubble_coral", count: [1, 64] },
                    { id: "fire_coral", count: [1, 64] },
                    { id: "horn_coral", count: [1, 64] },
                    { id: "dead_brain_coral", count: [1, 64] },
                    { id: "dead_bubble_coral", count: [1, 64] },
                    { id: "dead_fire_coral", count: [1, 64] },
                    { id: "dead_horn_coral", count: [1, 64] },
                    { id: "dead_tube_coral", count: [1, 64] },
                    { id: "tube_coral_fan", count: [1, 64] },
                    { id: "brain_coral_fan", count: [1, 64] },
                    { id: "bubble_coral_fan", count: [1, 64] },
                    { id: "fire_coral_fan", count: [1, 64] },
                    { id: "horn_coral_fan", count: [1, 64] },
                    { id: "dead_tube_coral_fan", count: [1, 64] },
                    { id: "dead_brain_coral_fan", count: [1, 64] },
                    { id: "dead_bubble_coral_fan", count: [1, 64] },
                    { id: "dead_fire_coral_fan", count: [1, 64] },
                    { id: "dead_horn_coral_fan", count: [1, 64] },
                    { id: "blue_ice", count: [1, 64] },
                    { id: "conduit", count: [1, 64] },
                    { id: "polished_granite_stairs", count: [1, 64] },
                    { id: "smooth_red_sandstone_stairs", count: [1, 64] },
                    { id: "mossy_stone_brick_stairs", count: [1, 64] },
                    { id: "polished_diorite_stairs", count: [1, 64] },
                    { id: "mossy_cobblestone_stairs", count: [1, 64] },
                    { id: "end_stone_brick_stairs", count: [1, 64] },
                    { id: "stone_stairs", count: [1, 64] },
                    { id: "smooth_sandstone_stairs", count: [1, 64] },
                    { id: "smooth_quartz_stairs", count: [1, 64] },
                    { id: "granite_stairs", count: [1, 64] },
                    { id: "andesite_stairs", count: [1, 64] },
                    { id: "red_nether_brick_stairs", count: [1, 64] },
                    { id: "polished_andesite_stairs", count: [1, 64] },
                    { id: "diorite_stairs", count: [1, 64] },
                    { id: "polished_granite_slab", count: [1, 64] },
                    { id: "smooth_red_sandstone_slab", count: [1, 64] },
                    { id: "mossy_stone_brick_slab", count: [1, 64] },
                    { id: "polished_diorite_slab", count: [1, 64] },
                    { id: "mossy_cobblestone_slab", count: [1, 64] },
                    { id: "end_stone_brick_slab", count: [1, 64] },
                    { id: "smooth_sandstone_slab", count: [1, 64] },
                    { id: "smooth_quartz_slab", count: [1, 64] },
                    { id: "granite_slab", count: [1, 64] },
                    { id: "andesite_slab", count: [1, 64] },
                    { id: "red_nether_brick_slab", count: [1, 64] },
                    { id: "polished_andesite_slab", count: [1, 64] },
                    { id: "diorite_slab", count: [1, 64] },
                    { id: "scaffolding", count: [1, 64] },
                    { id: "iron_door", count: [1, 64] },
                    { id: "oak_door", count: [1, 64] },
                    { id: "spruce_door", count: [1, 64] },
                    { id: "birch_door", count: [1, 64] },
                    { id: "jungle_door", count: [1, 64] },
                    { id: "acacia_door", count: [1, 64] },
                    { id: "dark_oak_door", count: [1, 64] },
                    { id: "repeater", count: [1, 64] },
                    { id: "comparator", count: [1, 64] },
                    { id: "structure_block", count: [1, 64] },
                    { id: "jigsaw", count: [1, 64] },
                    { id: "composter", count: [1, 64] },
                    { id: "turtle_helmet", count: [1, 64] },
                    { id: "scute", count: [1, 64] },
                    { id: "iron_shovel", count: [1, 64] },
                    { id: "iron_pickaxe", count: [1, 64] },
                    { id: "iron_axe", count: [1, 64] },
                    { id: "flint_and_steel", count: [1, 64] },
                    { id: "apple", count: [1, 64] },
                    { id: "bow", count: [1, 64] },
                    { id: "arrow", count: [1, 64] },
                    { id: "coal", count: [1, 64] },
                    { id: "charcoal", count: [1, 64] },
                    { id: "diamond", count: [1, 64] },
                    { id: "iron_ingot", count: [1, 64] },
                    { id: "gold_ingot", count: [1, 64] },
                    { id: "iron_sword", count: [1, 64] },
                    { id: "wooden_sword", count: [1, 64] },
                    { id: "wooden_shovel", count: [1, 64] },
                    { id: "wooden_pickaxe", count: [1, 64] },
                    { id: "wooden_axe", count: [1, 64] },
                    { id: "stone_sword", count: [1, 64] },
                    { id: "stone_shovel", count: [1, 64] },
                    { id: "stone_pickaxe", count: [1, 64] },
                    { id: "stone_axe", count: [1, 64] },
                    { id: "diamond_sword", count: [1, 64] },
                    { id: "diamond_shovel", count: [1, 64] },
                    { id: "diamond_pickaxe", count: [1, 64] },
                    { id: "diamond_axe", count: [1, 64] },
                    { id: "stick", count: [1, 64] },
                    { id: "bowl", count: [1, 64] },
                    { id: "mushroom_stew", count: [1, 64] },
                    { id: "golden_sword", count: [1, 64] },
                    { id: "golden_shovel", count: [1, 64] },
                    { id: "golden_pickaxe", count: [1, 64] },
                    { id: "golden_axe", count: [1, 64] },
                    { id: "string", count: [1, 64] },
                    { id: "feather", count: [1, 64] },
                    { id: "gunpowder", count: [1, 64] },
                    { id: "wooden_hoe", count: [1, 64] },
                    { id: "stone_hoe", count: [1, 64] },
                    { id: "iron_hoe", count: [1, 64] },
                    { id: "diamond_hoe", count: [1, 64] },
                    { id: "golden_hoe", count: [1, 64] },
                    { id: "wheat_seeds", count: [1, 64] },
                    { id: "wheat", count: [1, 64] },
                    { id: "bread", count: [1, 64] },
                    { id: "leather_helmet", count: [1, 64] },
                    { id: "leather_chestplate", count: [1, 64] },
                    { id: "leather_leggings", count: [1, 64] },
                    { id: "leather_boots", count: [1, 64] },
                    { id: "chainmail_helmet", count: [1, 64] },
                    { id: "chainmail_chestplate", count: [1, 64] },
                    { id: "chainmail_leggings", count: [1, 64] },
                    { id: "chainmail_boots", count: [1, 64] },
                    { id: "iron_helmet", count: [1, 64] },
                    { id: "iron_chestplate", count: [1, 64] },
                    { id: "iron_leggings", count: [1, 64] },
                    { id: "iron_boots", count: [1, 64] },
                    { id: "diamond_helmet", count: [1, 64] },
                    { id: "diamond_chestplate", count: [1, 64] },
                    { id: "diamond_leggings", count: [1, 64] },
                    { id: "diamond_boots", count: [1, 64] },
                    { id: "golden_helmet", count: [1, 64] },
                    { id: "golden_chestplate", count: [1, 64] },
                    { id: "golden_leggings", count: [1, 64] },
                    { id: "golden_boots", count: [1, 64] },
                    { id: "flint", count: [1, 64] },
                    { id: "porkchop", count: [1, 64] },
                    { id: "cooked_porkchop", count: [1, 64] },
                    { id: "painting", count: [1, 64] },
                    { id: "golden_apple", count: [1, 64] },
                    { id: "enchanted_golden_apple", count: [1, 64] },
                    { id: "oak_sign", count: [1, 64] },
                    { id: "spruce_sign", count: [1, 64] },
                    { id: "birch_sign", count: [1, 64] },
                    { id: "jungle_sign", count: [1, 64] },
                    { id: "acacia_sign", count: [1, 64] },
                    { id: "dark_oak_sign", count: [1, 64] },
                    { id: "bucket", count: [1, 64] },
                    { id: "water_bucket", count: [1, 64] },
                    { id: "lava_bucket", count: [1, 64] },
                    { id: "minecart", count: [1, 64] },
                    { id: "saddle", count: [1, 64] },
                    { id: "redstone", count: [1, 64] },
                    { id: "snowball", count: [1, 64] },
                    { id: "oak_boat", count: [1, 64] },
                    { id: "leather", count: [1, 64] },
                    { id: "milk_bucket", count: [1, 64] },
                    { id: "pufferfish_bucket", count: [1, 64] },
                    { id: "salmon_bucket", count: [1, 64] },
                    { id: "cod_bucket", count: [1, 64] },
                    { id: "tropical_fish_bucket", count: [1, 64] },
                    { id: "brick", count: [1, 64] },
                    { id: "clay_ball", count: [1, 64] },
                    { id: "sugar_cane", count: [1, 64] },
                    { id: "kelp", count: [1, 64] },
                    { id: "dried_kelp_block", count: [1, 64] },
                    { id: "bamboo", count: [1, 64] },
                    { id: "paper", count: [1, 64] },
                    { id: "book", count: [1, 64] },
                    { id: "slime_ball", count: [1, 64] },
                    { id: "chest_minecart", count: [1, 64] },
                    { id: "furnace_minecart", count: [1, 64] },
                    { id: "egg", count: [1, 64] },
                    { id: "compass", count: [1, 64] },
                    { id: "fishing_rod", count: [1, 64] },
                    { id: "clock", count: [1, 64] },
                    { id: "glowstone_dust", count: [1, 64] },
                    { id: "cod", count: [1, 64] },
                    { id: "salmon", count: [1, 64] },
                    { id: "tropical_fish", count: [1, 64] },
                    { id: "pufferfish", count: [1, 64] },
                    { id: "cooked_cod", count: [1, 64] },
                    { id: "cooked_salmon", count: [1, 64] },
                    { id: "ink_sac", count: [1, 64] },
                    { id: "red_dye", count: [1, 64] },
                    { id: "green_dye", count: [1, 64] },
                    { id: "cocoa_beans", count: [1, 64] },
                    { id: "lapis_lazuli", count: [1, 64] },
                    { id: "purple_dye", count: [1, 64] },
                    { id: "cyan_dye", count: [1, 64] },
                    { id: "light_gray_dye", count: [1, 64] },
                    { id: "gray_dye", count: [1, 64] },
                    { id: "pink_dye", count: [1, 64] },
                    { id: "lime_dye", count: [1, 64] },
                    { id: "yellow_dye", count: [1, 64] },
                    { id: "light_blue_dye", count: [1, 64] },
                    { id: "magenta_dye", count: [1, 64] },
                    { id: "orange_dye", count: [1, 64] },
                    { id: "bone_meal", count: [1, 64] },
                    { id: "blue_dye", count: [1, 64] },
                    { id: "brown_dye", count: [1, 64] },
                    { id: "black_dye", count: [1, 64] },
                    { id: "white_dye", count: [1, 64] },
                    { id: "bone", count: [1, 64] },
                    { id: "sugar", count: [1, 64] },
                    { id: "cake", count: [1, 64] },
                    { id: "white_bed", count: [1, 64] },
                    { id: "orange_bed", count: [1, 64] },
                    { id: "magenta_bed", count: [1, 64] },
                    { id: "light_blue_bed", count: [1, 64] },
                    { id: "yellow_bed", count: [1, 64] },
                    { id: "lime_bed", count: [1, 64] },
                    { id: "pink_bed", count: [1, 64] },
                    { id: "gray_bed", count: [1, 64] },
                    { id: "light_gray_bed", count: [1, 64] },
                    { id: "cyan_bed", count: [1, 64] },
                    { id: "purple_bed", count: [1, 64] },
                    { id: "blue_bed", count: [1, 64] },
                    { id: "brown_bed", count: [1, 64] },
                    { id: "green_bed", count: [1, 64] },
                    { id: "red_bed", count: [1, 64] },
                    { id: "black_bed", count: [1, 64] },
                    { id: "cookie", count: [1, 64] },
                    { id: "filled_map", count: [1, 64] },
                    { id: "shears", count: [1, 64] },
                    { id: "melon_slice", count: [1, 64] },
                    { id: "dried_kelp", count: [1, 64] },
                    { id: "pumpkin_seeds", count: [1, 64] },
                    { id: "melon_seeds", count: [1, 64] },
                    { id: "beef", count: [1, 64] },
                    { id: "cooked_beef", count: [1, 64] },
                    { id: "chicken", count: [1, 64] },
                    { id: "cooked_chicken", count: [1, 64] },
                    { id: "rotten_flesh", count: [1, 64] },
                    { id: "ender_pearl", count: [1, 64] },
                    { id: "blaze_rod", count: [1, 64] },
                    { id: "ghast_tear", count: [1, 64] },
                    { id: "gold_nugget", count: [1, 64] },
                    { id: "nether_wart", count: [1, 64] },
                    { id: "potion", count: [1, 64] },
                    { id: "glass_bottle", count: [1, 64] },
                    { id: "spider_eye", count: [1, 64] },
                    { id: "fermented_spider_eye", count: [1, 64] },
                    { id: "blaze_powder", count: [1, 64] },
                    { id: "magma_cream", count: [1, 64] },
                    { id: "brewing_stand", count: [1, 64] },
                    { id: "cauldron", count: [1, 64] },
                    { id: "ender_eye", count: [1, 64] },
                    { id: "glistering_melon_slice", count: [1, 64] },
                    { id: "bat_spawn_egg", count: [1, 64] },
                    { id: "bee_spawn_egg", count: [1, 64] },
                    { id: "blaze_spawn_egg", count: [1, 64] },
                    { id: "cat_spawn_egg", count: [1, 64] },
                    { id: "cave_spider_spawn_egg", count: [1, 64] },
                    { id: "chicken_spawn_egg", count: [1, 64] },
                    { id: "cod_spawn_egg", count: [1, 64] },
                    { id: "cow_spawn_egg", count: [1, 64] },
                    { id: "creeper_spawn_egg", count: [1, 64] },
                    { id: "dolphin_spawn_egg", count: [1, 64] },
                    { id: "donkey_spawn_egg", count: [1, 64] },
                    { id: "drowned_spawn_egg", count: [1, 64] },
                    { id: "elder_guardian_spawn_egg", count: [1, 64] },
                    { id: "enderman_spawn_egg", count: [1, 64] },
                    { id: "endermite_spawn_egg", count: [1, 64] },
                    { id: "evoker_spawn_egg", count: [1, 64] },
                    { id: "fox_spawn_egg", count: [1, 64] },
                    { id: "ghast_spawn_egg", count: [1, 64] },
                    { id: "guardian_spawn_egg", count: [1, 64] },
                    { id: "horse_spawn_egg", count: [1, 64] },
                    { id: "husk_spawn_egg", count: [1, 64] },
                    { id: "llama_spawn_egg", count: [1, 64] },
                    { id: "magma_cube_spawn_egg", count: [1, 64] },
                    { id: "mooshroom_spawn_egg", count: [1, 64] },
                    { id: "mule_spawn_egg", count: [1, 64] },
                    { id: "ocelot_spawn_egg", count: [1, 64] },
                    { id: "panda_spawn_egg", count: [1, 64] },
                    { id: "parrot_spawn_egg", count: [1, 64] },
                    { id: "phantom_spawn_egg", count: [1, 64] },
                    { id: "pig_spawn_egg", count: [1, 64] },
                    { id: "pillager_spawn_egg", count: [1, 64] },
                    { id: "polar_bear_spawn_egg", count: [1, 64] },
                    { id: "pufferfish_spawn_egg", count: [1, 64] },
                    { id: "rabbit_spawn_egg", count: [1, 64] },
                    { id: "ravager_spawn_egg", count: [1, 64] },
                    { id: "salmon_spawn_egg", count: [1, 64] },
                    { id: "sheep_spawn_egg", count: [1, 64] },
                    { id: "shulker_spawn_egg", count: [1, 64] },
                    { id: "silverfish_spawn_egg", count: [1, 64] },
                    { id: "skeleton_spawn_egg", count: [1, 64] },
                    { id: "skeleton_horse_spawn_egg", count: [1, 64] },
                    { id: "slime_spawn_egg", count: [1, 64] },
                    { id: "spider_spawn_egg", count: [1, 64] },
                    { id: "squid_spawn_egg", count: [1, 64] },
                    { id: "stray_spawn_egg", count: [1, 64] },
                    { id: "trader_llama_spawn_egg", count: [1, 64] },
                    { id: "tropical_fish_spawn_egg", count: [1, 64] },
                    { id: "turtle_spawn_egg", count: [1, 64] },
                    { id: "vex_spawn_egg", count: [1, 64] },
                    { id: "villager_spawn_egg", count: [1, 64] },
                    { id: "vindicator_spawn_egg", count: [1, 64] },
                    { id: "wandering_trader_spawn_egg", count: [1, 64] },
                    { id: "witch_spawn_egg", count: [1, 64] },
                    { id: "wither_skeleton_spawn_egg", count: [1, 64] },
                    { id: "wolf_spawn_egg", count: [1, 64] },
                    { id: "zombie_spawn_egg", count: [1, 64] },
                    { id: "zombie_horse_spawn_egg", count: [1, 64] },
                    { id: "zombie_pigman_spawn_egg", count: [1, 64] },
                    { id: "zombie_villager_spawn_egg", count: [1, 64] },
                    { id: "experience_bottle", count: [1, 64] },
                    { id: "fire_charge", count: [1, 64] },
                    { id: "writable_book", count: [1, 64] },
                    { id: "written_book", count: [1, 64] },
                    { id: "emerald", count: [1, 64] },
                    { id: "item_frame", count: [1, 64] },
                    { id: "flower_pot", count: [1, 64] },
                    { id: "carrot", count: [1, 64] },
                    { id: "potato", count: [1, 64] },
                    { id: "baked_potato", count: [1, 64] },
                    { id: "poisonous_potato", count: [1, 64] },
                    { id: "map", count: [1, 64] },
                    { id: "golden_carrot", count: [1, 64] },
                    { id: "skeleton_skull", count: [1, 64] },
                    { id: "wither_skeleton_skull", count: [1, 64] },
                    { id: "player_head", count: [1, 64] },
                    { id: "zombie_head", count: [1, 64] },
                    { id: "creeper_head", count: [1, 64] },
                    { id: "dragon_head", count: [1, 64] },
                    { id: "carrot_on_a_stick", count: [1, 64] },
                    { id: "nether_star", count: [1, 64] },
                    { id: "pumpkin_pie", count: [1, 64] },
                    { id: "firework_rocket", count: [1, 64] },
                    { id: "firework_star", count: [1, 64] },
                    { id: "enchanted_book", count: [1, 64] },
                    { id: "nether_brick", count: [1, 64] },
                    { id: "quartz", count: [1, 64] },
                    { id: "tnt_minecart", count: [1, 64] },
                    { id: "hopper_minecart", count: [1, 64] },
                    { id: "prismarine_shard", count: [1, 64] },
                    { id: "prismarine_crystals", count: [1, 64] },
                    { id: "rabbit", count: [1, 64] },
                    { id: "cooked_rabbit", count: [1, 64] },
                    { id: "rabbit_stew", count: [1, 64] },
                    { id: "rabbit_foot", count: [1, 64] },
                    { id: "rabbit_hide", count: [1, 64] },
                    { id: "armor_stand", count: [1, 64] },
                    { id: "iron_horse_armor", count: [1, 64] },
                    { id: "golden_horse_armor", count: [1, 64] },
                    { id: "diamond_horse_armor", count: [1, 64] },
                    { id: "leather_horse_armor", count: [1, 64] },
                    { id: "lead", count: [1, 64] },
                    { id: "name_tag", count: [1, 64] },
                    { id: "command_block_minecart", count: [1, 64] },
                    { id: "mutton", count: [1, 64] },
                    { id: "cooked_mutton", count: [1, 64] },
                    { id: "white_banner", count: [1, 64] },
                    { id: "orange_banner", count: [1, 64] },
                    { id: "magenta_banner", count: [1, 64] },
                    { id: "light_blue_banner", count: [1, 64] },
                    { id: "yellow_banner", count: [1, 64] },
                    { id: "lime_banner", count: [1, 64] },
                    { id: "pink_banner", count: [1, 64] },
                    { id: "gray_banner", count: [1, 64] },
                    { id: "light_gray_banner", count: [1, 64] },
                    { id: "cyan_banner", count: [1, 64] },
                    { id: "purple_banner", count: [1, 64] },
                    { id: "blue_banner", count: [1, 64] },
                    { id: "brown_banner", count: [1, 64] },
                    { id: "green_banner", count: [1, 64] },
                    { id: "red_banner", count: [1, 64] },
                    { id: "black_banner", count: [1, 64] },
                    { id: "end_crystal", count: [1, 64] },
                    { id: "chorus_fruit", count: [1, 64] },
                    { id: "popped_chorus_fruit", count: [1, 64] },
                    { id: "beetroot", count: [1, 64] },
                    { id: "beetroot_seeds", count: [1, 64] },
                    { id: "beetroot_soup", count: [1, 64] },
                    { id: "dragon_breath", count: [1, 64] },
                    { id: "splash_potion", count: [1, 64] },
                    { id: "spectral_arrow", count: [1, 64] },
                    { id: "tipped_arrow", count: [1, 64] },
                    { id: "lingering_potion", count: [1, 64] },
                    { id: "shield", count: [1, 64] },
                    { id: "elytra", count: [1, 64] },
                    { id: "spruce_boat", count: [1, 64] },
                    { id: "birch_boat", count: [1, 64] },
                    { id: "jungle_boat", count: [1, 64] },
                    { id: "acacia_boat", count: [1, 64] },
                    { id: "dark_oak_boat", count: [1, 64] },
                    { id: "totem_of_undying", count: [1, 64] },
                    { id: "shulker_shell", count: [1, 64] },
                    { id: "iron_nugget", count: [1, 64] },
                    { id: "knowledge_book", count: [1, 64] },
                    { id: "debug_stick", count: [1, 64] },
                    { id: "music_disc_13", count: [1, 64] },
                    { id: "music_disc_cat", count: [1, 64] },
                    { id: "music_disc_blocks", count: [1, 64] },
                    { id: "music_disc_chirp", count: [1, 64] },
                    { id: "music_disc_far", count: [1, 64] },
                    { id: "music_disc_mall", count: [1, 64] },
                    { id: "music_disc_mellohi", count: [1, 64] },
                    { id: "music_disc_stal", count: [1, 64] },
                    { id: "music_disc_strad", count: [1, 64] },
                    { id: "music_disc_ward", count: [1, 64] },
                    { id: "music_disc_11", count: [1, 64] },
                    { id: "music_disc_wait", count: [1, 64] },
                    { id: "trident", count: [1, 64] },
                    { id: "phantom_membrane", count: [1, 64] },
                    { id: "nautilus_shell", count: [1, 64] },
                    { id: "heart_of_the_sea", count: [1, 64] },
                    { id: "crossbow", count: [1, 64] },
                    { id: "suspicious_stew", count: [1, 64] },
                    { id: "loom", count: [1, 64] },
                    { id: "flower_banner_pattern", count: [1, 64] },
                    { id: "creeper_banner_pattern", count: [1, 64] },
                    { id: "skull_banner_pattern", count: [1, 64] },
                    { id: "mojang_banner_pattern", count: [1, 64] },
                    { id: "globe_banner_pattern", count: [1, 64] },
                    { id: "barrel", count: [1, 64] },
                    { id: "smoker", count: [1, 64] },
                    { id: "blast_furnace", count: [1, 64] },
                    { id: "cartography_table", count: [1, 64] },
                    { id: "fletching_table", count: [1, 64] },
                    { id: "grindstone", count: [1, 64] },
                    { id: "lectern", count: [1, 64] },
                    { id: "smithing_table", count: [1, 64] },
                    { id: "stonecutter", count: [1, 64] },
                    { id: "bell", count: [1, 64] },
                    { id: "lantern", count: [1, 64] },
                    { id: "sweet_berries", count: [1, 64] },
                    { id: "campfire", count: [1, 64] },
                    { id: "honeycomb", count: [1, 64] },
                    { id: "bee_nest", count: [1, 64] },
                    { id: "beehive", count: [1, 64] },
                    { id: "honey_bottle", count: [1, 64] },
                    { id: "honey_block", count: [1, 64] },
                    { id: "honeycomb_block", count: [1, 64] },

                    //Custom Items
                    // Example Item
                    { id: "minecraft:diamond_block", count: [1, 10], tag: { display: { Name: '{"text":"Shiny Block"}' } } },
                    // Custom Sword
                    { id: "minecraft:diamond_sword", count: [1, 1], tag: { display: { Name: '{"text":"Sharp Sword"}' }, Enchantments: [{id: "minecraft:sharpness", lvl: 5}] } },
                    // Bottle o' Cum
                    {
                        id: "minecraft:potion",
                        count: [1, 1],
                        tag: {
                            display: {
                                Name: '{"text":"Bottle o\' cum","color":"white","bold":true}',
                                Lore: ['{"text":"Straight from SC09\'s factories"}']
                            },
                            HideFlags:2,
                            CustomPotionEffects: [
                                {Id: 1, Amplifier: "3b", Duration: -1, ShowParticles: "0b"},
                                {Id: 3, Amplifier: "3b", Duration: -1, ShowParticles: "0b"},
                                {Id: 5, Amplifier: "3b", Duration: -1, ShowParticles: "0b"},
                                {Id: 6, Amplifier: "3b", Duration: -1, ShowParticles: "0b"},
                                {Id: 8, Amplifier: "3b", Duration: -1, ShowParticles: "0b"},
                                {Id: 10, Amplifier: "3b", Duration: -1, ShowParticles: "0b"},
                                {Id: 11, Amplifier: "3b", Duration: -1, ShowParticles: "0b"}
                            ],
                            CustomPotionColor: 16777215
                        }
                    },
                    // Custom Sword
                    {
                        id: "minecraft:netherite_sword",
                        count: [1, 64],
                        Damage:0,
                        Enchantments:[{id:"minecraft:fire_aspect",lvl:"255s"},{id:"minecraft:sharpness",lvl:"255s"}],
                        display:{
                            Lore:['{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"Radiant 1000000000"}],"text":""}',
                                '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"Rage 1000000000"}],"text":""}',
                                '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"SlowMo 1000000000"}],"text":""}'],
                            Name:'{"extra":[{"bold":true,"italic":false,"underlined":true,"strikethrough":false,"obfuscated":false,"color":"dark_red","text":" ❤ Heart Decapitator ❤"}],"text":""}'
                        }
                    },
                    // Book of math
                    {
                        id: "written_book",
                        count: [1, 64],
                        pages:[
                            '{"text":"Mathematics begins with basic arithmetic operations, which are addition, subtraction, multiplication, and division. Addition involves combining two or more numbers to get a total, for example, 2+3=52 + 3 = 52+3=5. Subtraction is the process of removing one number from another, such as 5\\u22122=35 - 2 = 35\\u22122=3. "}',
                            '{"text":"Multiplication is repeated addition of a number, like 4×3=124 \\\\times 3 = 124×3=12, and division involves splitting a number into equal parts, for instance, 12÷3=412 ÷ 3 = 412÷3=4. Moving on to number types, we have integers, which include whole numbers and their negatives, such as \\u22123,0,4-3, 0, 4\\u22123,0,4, and "}',
                            '{"text":"fractions, which represent parts of a whole, like 12\\\\frac{1}{2}21\\u200b or 34\\\\frac{3}{4}43\\u200b. Decimals are another form of representing fractions, using a decimal point, such as 0.5 or 3.75. As we progress, we encounter the concept of exponents, where a number is raised to the power of another,"}',
                            '{"text":"like 23=82^3 = 823=8. The opposite operation is finding roots, for example, the square root of 9 is 3 (9=3\\\\sqrt{9} = 39\\u200b=3). Algebra introduces variables, which are symbols representing numbers, and allows us to solve equations like x+2=5x + 2 = 5x+2=5, where x=3x = 3x=3. Expressions combine numbers, "}',
                            '{"text":"variables, and operations, and can be simplified using rules of arithmetic. In more advanced algebra, we solve systems of equations and work with inequalities, which show relationships between expressions, such as x>2x > 2x>2. Geometry is the study of shapes and their properties. It includes "}',
                            '{"text":"points, lines, angles, and shapes like triangles, squares, and circles. The Pythagorean theorem is a fundamental principle in geometry, stating that in a right-angled triangle, the square of the hypotenuse is equal to the sum of the squares of the other two sides (a2+b2=c2a^2 + b^2 ="}',
                            '{"text":"c^2a2+b2=c2). Trigonometry deals with the relationships between the angles and sides of triangles, introducing functions like sine, cosine, and tangent, which are essential in understanding waves and oscillations. Calculus, a branch of mathematics developed by Newton and Leibniz, studies change and "}',
                            '{"text":"motion. It has two main parts: differential calculus and integral calculus. Differential calculus focuses on finding the rate of change of a function, known as the derivative, while integral calculus deals with finding the total accumulation of a quantity, known as the integral. These concepts are crucial "}',
                            '{"text":"in physics, engineering, and economics for modeling and solving problems involving change Finally, statistics and probability involve the study of data and uncertainty. Statistics includes collecting, analyzing, interpreting, and presenting data, using measures like mean, median, mode, and standard deviation "}',
                            '{"text":"to summarize information. Probability deals with the likelihood of events occurring, with concepts like independent and dependent events, and the use of probability distributions to model random processes. Together, these areas form the foundation of modern data science and are essential for "}',
                            '{"text":"making informed decisions based on data"}'],
                        title: "Math",
                        author: "SC09 - Random Loot",
                        generation:3
                    },
                    // Book of mc history
                    {
                        id: "written_book",
                        count: [1, 64],
                        pages:['{"text":"Minecraft, conceived by Markus \\"Notch\\" Persson, began development in May 2009 under the project name \\"Cave Game.\\" It evolved through alpha and beta phases, showcasing basic gameplay mechanics like mining, crafting, and building. The game gained early popularity through its "}',
                            '{"text":"unique sandbox concept and was officially released on November 18, 2011, during MineCon in Las Vegas, introducing features such as the \\"End\\" dimension and the defeat of the Ender Dragon. Following its launch, Minecraft continued to expand with major updates, including new biomes, "}',
                            '{"text":"creatures, and gameplay modes. Microsoft acquired Mojang Studios, the developer of Minecraft, in September 2014 for $2.5 billion, aiming to enhance the game\'s accessibility and integrate it into its gaming ecosystem. This acquisition led to significant advancements in "}',
                            '{"text":"cross-platform play, enabling players on different devices to interact in the same Minecraft world seamlessly. Minecraft transcended gaming to become a cultural phenomenon, influencing education and popular culture. Its open-world, creative gameplay inspired a vibrant community of players "}',
                            '{"text":"who built expansive creations, developed mods, and shared their experiences online. The game\'s educational potential was formalized with \\"Minecraft: Education Edition,\\" used globally to teach subjects like history, math, and programming through interactive gameplay. \\u200bContinued development by Mojang has "}',
                            '{"text":"ensured Minecraft\'s relevance and engagement. Regular updates introduce new content, optimizations, and community-requested features, fostering an active player base and a thriving modding community. Minecraft\'s journey from indie project to global sensation underscores its "}',
                            '{"text":"enduring appeal and impact on modern gaming, making it a beloved title enjoyed by millions worldwide across PC, consoles, and mobile platforms."}'],
                        title:"The History of Minecraft",
                        author:"SC09 - Random Loot",
                        generation:3
                    }
                ];

                const maxItems = 27; // Maximum number of items in a single chest
                const chestItems = [];
                const usedSlots = new Set();

                // Randomly decide the number of items (between 1 and maxItems)
                const itemCount = getRandomInt(1, maxItems + 1);

                for (let i = 0; i < itemCount; i++) {
                    const itemData = items[getRandomInt(0, items.length)];
                    const item = itemData.id;
                    const count = getRandomInt(itemData.count[0], itemData.count[1] + 1);
                    let slot;

                    // Ensure each item is placed in a unique slot
                    do {
                        slot = getRandomInt(0, maxItems);
                    } while (usedSlots.has(slot));

                    usedSlots.add(slot);

                    let itemString = `{Slot:${slot}b,id:"${item}",Count:${count}b}`;
                    if (itemData.tag) {
                        itemString = `{Slot:${slot}b,id:"${item}",Count:${count}b,tag:${JSON.stringify(itemData.tag)}}`;
                    }

                    chestItems.push(itemString);
                }

                const itemsTag = chestItems.join(",");
                core.run(`/execute at ${senderUUID} run setblock ~ ~ ~ minecraft:chest[type=single]{Items:[${itemsTag}],CustomName:'{"text":"Random Loot Chest - SC09"}'} destroy`);
                core.run((new Tellraw("@a", [new Text(`Here is your loot`).setColor(colors.primary)])).get());
            }

            generateRandomChest();

        } catch (error) {
            const core = context.core
            core.run((new Tellraw("@a", [new Text(`ERROR - ` + error).setColor(colors.errorColor).setHover(error.stack).setCopy(error.stack)])).get());
        }
        return context;
    }
};

/*
Context includes:
- client
- core
- cloop
- args
- senderUUID
- username
- hash
- ownerHash
- currentServer
- config
*/